# Imports and Setup

In [1]:
# Imports
import os
import dotenv
import re
import pandas as pd
from googleapiclient.discovery import build
from youtube_transcript_api import YouTubeTranscriptApi
from datetime import datetime, timezone

In [6]:
# Load environment variables
dotenv.load_dotenv()

True

In [7]:
# Get the API key 
API_KEY = os.getenv("YOUTUBE_API_KEY")

# Set up the YouTube Data API client 
youtube = build("youtube", "v3", developerKey=API_KEY)

In [8]:
# Define the channel ID
SKZ_CHANNEL_ID = "UC9rMiEjNaCSsebs31MRDCRA"

# Map the base Channel ID to the specific hidden playlists
base_id = SKZ_CHANNEL_ID.replace("UC", "")
playlists_to_process = {
    "Long-form": f"UULF{base_id}",
    "Short": f"UUSH{base_id}",
    "Live/VOD": f"UULV{base_id}"
}

In [9]:
playlists_to_process.get("Long-form")

'UULF9rMiEjNaCSsebs31MRDCRA'

# Fetching Video IDs

In [ ]:
# Fetch Longform Video IDs via Pagination
# For testing, limit this to just 2 pages (2 x 50 videos)
longform_playlist_id = playlists_to_process.get("Long-form")

video_ids = []
next_page_token = None

response_1 = youtube.playlistItems().list(
    part="contentDetails",
    playlistId=longform_playlist_id,
    maxResults=50,
    pageToken=next_page_token
).execute()
display(response_1)

{'kind': 'youtube#playlistItemListResponse',
 'etag': 'ejzbVvl0_KLUTybNZ5Qf6qAj7RY',
 'nextPageToken': 'EAAaHlBUOkNESWlFRFpCUVRFMU9UTTJNalpDTkRaRU5EVQ',
 'items': [{'kind': 'youtube#playlistItem',
   'etag': 'Pgpq1cPtVhIWHDtLy4ciXHRghyE',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEubDhzU1FBYTFrTk0',
   'contentDetails': {'videoId': 'l8sSQAa1kNM',
    'videoPublishedAt': '2026-03-19T15:00:08Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'oFU16bh108UH8TWcJCCC9sveSiY',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuOURTT0Z5TFN2NlE',
   'contentDetails': {'videoId': '9DSOFyLSv6Q',
    'videoPublishedAt': '2026-03-19T10:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '10XJoKMDlGcDgkkTKbhB6EmkAUI',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuSmw1bk5xYWpyVjA',
   'contentDetails': {'videoId': 'Jl5nNqajrV0',
    'videoPublishedAt': '2026-03-18T10:59:56Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'E--JGQz9mGk_qs9A6DTov7_GU5k',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuMXRpcGsyWDFhVW8',
   'contentDetails': {'videoId': '1tipk2X1aUo',
    'videoPublishedAt': '2026-03-17T10:59:56Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'nM2yJxVNY4muDJyiuE0x_uGxJaI',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuYkRielpfRHg0S3M',
   'contentDetails': {'videoId': 'bDbzZ_Dx4Ks',
    'videoPublishedAt': '2026-03-15T11:00:18Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'HnnUcqM9upfYH8hLpNTUMPym9Jw',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudUItWFBlMUs3U1U',
   'contentDetails': {'videoId': 'uB-XPe1K7SU',
    'videoPublishedAt': '2026-03-12T10:59:56Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '84nHAQtEm9zIHdOx0cI7JCK13oQ',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWDdqQW1zX2Y0UmM',
   'contentDetails': {'videoId': 'X7jAms_f4Rc',
    'videoPublishedAt': '2026-03-10T11:00:03Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '9BjuYpLAYby2Oyh291ZamQfv4FA',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuYlNaTDNaWkM4RUU',
   'contentDetails': {'videoId': 'bSZL3ZZC8EE',
    'videoPublishedAt': '2026-03-07T15:00:00Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '9HzHQ816GkDBdp5kM0IHIzoJAqE',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEubzY2S0pYMVlKM3M',
   'contentDetails': {'videoId': 'o66KJX1YJ3s',
    'videoPublishedAt': '2026-03-05T10:59:57Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '1fjiSTI4Q4xwnYHjJ0EtQXjhDfU',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWlY1SWpOZ3BCRlE',
   'contentDetails': {'videoId': 'ZV5IjNgpBFQ',
    'videoPublishedAt': '2026-03-04T10:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'rgSL6i6bwLtC8-S-Wr2cpStG8eI',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuc0tpMWdFdG5TQVE',
   'contentDetails': {'videoId': 'sKi1gEtnSAQ',
    'videoPublishedAt': '2026-03-04T06:25:03Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'NZebeNbm9JLpHbioN-7wtPJANDA',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEueC1rbDdmekVtYVk',
   'contentDetails': {'videoId': 'x-kl7fzEmaY',
    'videoPublishedAt': '2026-02-28T10:59:59Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'qOx74odQiRmWrm_ryYiLlD98xsI',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuaDFsaTNObFRCMEk',
   'contentDetails': {'videoId': 'h1li3NlTB0I',
    'videoPublishedAt': '2026-02-26T10:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '3iDct6XiSRXqpo7rE6UOXEXCab0',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuT0RvRWFfMWdQU2M',
   'contentDetails': {'videoId': 'ODoEa_1gPSc',
    'videoPublishedAt': '2026-02-20T11:00:04Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'AVfu8c4WUV8UCtq_2sVw-s8lcJk',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuSEZiaXJBRFUzX1E',
   'contentDetails': {'videoId': 'HFbirADU3_Q',
    'videoPublishedAt': '2026-02-19T10:59:57Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '-HuOb07iwIN-mZJnqb8CVnUNhoQ',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuRkVEUTE0dDU4Q0E',
   'contentDetails': {'videoId': 'FEDQ14t58CA',
    'videoPublishedAt': '2026-02-16T02:59:57Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'gkzmJwirQYNo2ZfOv3j1yEo8ob0',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEubVVGS1VKVE1qV2c',
   'contentDetails': {'videoId': 'mUFKUJTMjWg',
    'videoPublishedAt': '2026-02-12T10:59:57Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'n0lPA8WRc7H-MWOIW9vJYaW9pOQ',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuUFVVeEU3RUdQNFE',
   'contentDetails': {'videoId': 'PUUxE7EGP4Q',
    'videoPublishedAt': '2026-02-10T06:25:00Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'm5ralviK1LCbvakF804naK_lfPs',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuT1NVSHFBdnVTUkk',
   'contentDetails': {'videoId': 'OSUHqAvuSRI',
    'videoPublishedAt': '2026-01-31T15:00:00Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'TuRpR4ztXyBCeg632AiS4WrGeaA',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuRjZsZjI2bldrMTA',
   'contentDetails': {'videoId': 'F6lf26nWk10',
    'videoPublishedAt': '2026-01-31T04:00:04Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'jE8qqA1EDBdod6P8bwYr1fPsG5w',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuVHNyM2xCRW45d3c',
   'contentDetails': {'videoId': 'Tsr3lBEn9ww',
    'videoPublishedAt': '2026-01-28T14:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'L_RAwmvjjQTbrwFZjkdZrl9Jd_0',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuSWlxb296Rk9zMXM',
   'contentDetails': {'videoId': 'IiqoozFOs1s',
    'videoPublishedAt': '2026-01-27T10:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'lMviuFdL0nB5R0OQ5ANYJGhSu9Y',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudjF4bTZQY2stbW8',
   'contentDetails': {'videoId': 'v1xm6Pck-mo',
    'videoPublishedAt': '2026-01-21T10:59:59Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'd2NsBQ9yPn60hhRWkb3NPQQwuiQ',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWE9jSDNsZ3cwS0U',
   'contentDetails': {'videoId': 'XOcH3lgw0KE',
    'videoPublishedAt': '2026-01-20T04:00:01Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'Ed-6ZpNG8X9JaLnn4A08UbsXSEo',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuYnBuYWIwQWE1bUU',
   'contentDetails': {'videoId': 'bpnab0Aa5mE',
    'videoPublishedAt': '2026-01-14T11:00:01Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'M3FWucjccljm9mkLJKn5s8z7Q1M',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuZkVUamdZODNvN1E',
   'contentDetails': {'videoId': 'fETjgY83o7Q',
    'videoPublishedAt': '2026-01-12T10:59:56Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'PuSpCr-yS7X6SymZqfiRp91-evQ',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudXJOTFBnYWx0Nm8',
   'contentDetails': {'videoId': 'urNLPgalt6o',
    'videoPublishedAt': '2026-01-07T11:00:03Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'Zx6sGoUhJUPt4qXZqeYnoOK_BB4',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuOWJISmM1SHY5Vnc',
   'contentDetails': {'videoId': '9bHJc5Hv9Vw',
    'videoPublishedAt': '2026-01-05T10:59:56Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'mO2mJFgqm_2Kbe_8R2Nb9Nxo1GE',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuNU9pbzE0NVdCQjg',
   'contentDetails': {'videoId': '5Oio145WBB8',
    'videoPublishedAt': '2025-12-31T15:00:01Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'xxfAsd1vhbuJqNw5EJeH5J_jcGo',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEubnY2V3RObVBYWlU',
   'contentDetails': {'videoId': 'nv6WtNmPXZU',
    'videoPublishedAt': '2025-12-29T11:00:01Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '_pTUjz58TE6gYR4_IQ8Ii4FkG7M',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWXN2Yk42NjVMWkU',
   'contentDetails': {'videoId': 'YsvbN665LZE',
    'videoPublishedAt': '2025-12-27T14:00:00Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'eLDu4cHd3wX6ztgaiOxWcdttZNg',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWmVvSHMyemZYUEU',
   'contentDetails': {'videoId': 'ZeoHs2zfXPE',
    'videoPublishedAt': '2025-12-24T10:59:57Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'pEQ1tGmMog4q27tRFT0ciovlqzo',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEud2dmUGtXU0RVSFU',
   'contentDetails': {'videoId': 'wgfPkWSDUHU',
    'videoPublishedAt': '2025-12-22T10:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'ecxQNLrnPYq7vvyUTMYKw8fLLnQ',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuTUk2X2FIMUpUN3M',
   'contentDetails': {'videoId': 'MI6_aH1JT7s',
    'videoPublishedAt': '2025-12-21T11:59:59Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'h3d2xvJUUAVB6AiqP4rcbGLBuEI',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuSGRncEgzX21aRXM',
   'contentDetails': {'videoId': 'HdgpH3_mZEs',
    'videoPublishedAt': '2025-12-19T10:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '-E_5EREPoGVZAtvsTMwmjspH9HQ',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuZHhpNHBCOWI3ZWc',
   'contentDetails': {'videoId': 'dxi4pB9b7eg',
    'videoPublishedAt': '2025-12-17T10:59:57Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'rEtFtNXkZM1Y9rkpIb5v4Bnkvmw',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudVJKVVZVbFRldk0',
   'contentDetails': {'videoId': 'uRJUVUlTevM',
    'videoPublishedAt': '2025-12-15T10:59:57Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '35urR_kWUXMxYgI6ZRhNpJJEOQg',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuUEVUMzk2TUNJVjg',
   'contentDetails': {'videoId': 'PET396MCIV8',
    'videoPublishedAt': '2025-12-13T10:59:59Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'ug_qHovj1Pki_8KwSkLH0FSq6SM',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuVEE3QzJOQll3ODg',
   'contentDetails': {'videoId': 'TA7C2NBYw88',
    'videoPublishedAt': '2025-12-12T11:00:01Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'OBHNkmjYJKKANOwHuDnNEAH5ICM',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuM3oyN2pPZ1h4LUk',
   'contentDetails': {'videoId': '3z27jOgXx-I',
    'videoPublishedAt': '2025-12-11T10:59:57Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '5QHVOPRZqSId4ffcZ1OFzXp0Jjk',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuNWJ6SGVTcGhnVVU',
   'contentDetails': {'videoId': '5bzHeSphgUU',
    'videoPublishedAt': '2025-12-09T10:59:59Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '52rCCo905c1tsWDD-hsznn_a8nQ',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWnFuQkNoNTFxVXc',
   'contentDetails': {'videoId': 'ZqnBCh51qUw',
    'videoPublishedAt': '2025-12-08T10:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'vVQXhUwuRMXxgYyQTitB41065so',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuUU5LVFpTWi1YM3M',
   'contentDetails': {'videoId': 'QNKTZSZ-X3s',
    'videoPublishedAt': '2025-12-07T10:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'BEr5rwi9penLrywYnRAH_KB7y88',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuRlI5OU9seE9WdXM',
   'contentDetails': {'videoId': 'FR99OlxOVus',
    'videoPublishedAt': '2025-12-05T11:00:00Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '0CVXEk-c0gdIVE0U-KVydVkXto0',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEueHF1OWVlR1F4WGM',
   'contentDetails': {'videoId': 'xqu9eeGQxXc',
    'videoPublishedAt': '2025-12-04T10:59:58Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '5JlEqyrMA0ZWpK84A6x-TLyI_40',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuN294SlNyTjJDTlE',
   'contentDetails': {'videoId': '7oxJSrN2CNQ',
    'videoPublishedAt': '2025-12-03T10:59:56Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'H-ccgMDOz1biKB3Dwrp3xDFfC60',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudlBQRWZMdjFFcEU',
   'contentDetails': {'videoId': 'vPPEfLv1EpE',
    'videoPublishedAt': '2025-12-02T11:00:00Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': 'uku8YvDSbrCFC0sdNYcqVb5Fe10',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuazRJc0pEd1JLejQ',
   'contentDetails': {'videoId': 'k4IsJDwRKz4',
    'videoPublishedAt': '2025-12-01T11:00:01Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '2GKegGusnicwwTr1R4RXjtimoew',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudWRGaWlSNFY2bWc',
   'contentDetails': {'videoId': 'udFiiR4V6mg',
    'videoPublishedAt': '2025-12-01T03:00:03Z'}},
  {'kind': 'youtube#playlistItem',
   'etag': '3hvbaBUmYAxouR5Nc9R-o6uJJZc',
   'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEud0lKMlRjbkRLUHM',
   'contentDetails': {'videoId': 'wIJ2TcnDKPs',
    'videoPublishedAt': '2025-11-28T11:00:01Z'}}],
 'pageInfo': {'totalResults': 1085, 'resultsPerPage': 50}}

In [7]:
# Get the list of playllist items
print(len(response_1["items"]), " values")
display(response_1["items"])

50  values

[{'kind': 'youtube#playlistItem',
  'etag': 'Pgpq1cPtVhIWHDtLy4ciXHRghyE',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEubDhzU1FBYTFrTk0',
  'contentDetails': {'videoId': 'l8sSQAa1kNM',
   'videoPublishedAt': '2026-03-19T15:00:08Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'oFU16bh108UH8TWcJCCC9sveSiY',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuOURTT0Z5TFN2NlE',
  'contentDetails': {'videoId': '9DSOFyLSv6Q',
   'videoPublishedAt': '2026-03-19T10:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '10XJoKMDlGcDgkkTKbhB6EmkAUI',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuSmw1bk5xYWpyVjA',
  'contentDetails': {'videoId': 'Jl5nNqajrV0',
   'videoPublishedAt': '2026-03-18T10:59:56Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'E--JGQz9mGk_qs9A6DTov7_GU5k',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuMXRpcGsyWDFhVW8',
  'contentDetails': {'videoId': '1tipk2X1aUo',
   'videoPublishedAt': '2026-03-17T10:59:56Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'nM2yJxVNY4muDJyiuE0x_uGxJaI',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuYkRielpfRHg0S3M',
  'contentDetails': {'videoId': 'bDbzZ_Dx4Ks',
   'videoPublishedAt': '2026-03-15T11:00:18Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'HnnUcqM9upfYH8hLpNTUMPym9Jw',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudUItWFBlMUs3U1U',
  'contentDetails': {'videoId': 'uB-XPe1K7SU',
   'videoPublishedAt': '2026-03-12T10:59:56Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '84nHAQtEm9zIHdOx0cI7JCK13oQ',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWDdqQW1zX2Y0UmM',
  'contentDetails': {'videoId': 'X7jAms_f4Rc',
   'videoPublishedAt': '2026-03-10T11:00:03Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '9BjuYpLAYby2Oyh291ZamQfv4FA',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuYlNaTDNaWkM4RUU',
  'contentDetails': {'videoId': 'bSZL3ZZC8EE',
   'videoPublishedAt': '2026-03-07T15:00:00Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '9HzHQ816GkDBdp5kM0IHIzoJAqE',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEubzY2S0pYMVlKM3M',
  'contentDetails': {'videoId': 'o66KJX1YJ3s',
   'videoPublishedAt': '2026-03-05T10:59:57Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '1fjiSTI4Q4xwnYHjJ0EtQXjhDfU',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWlY1SWpOZ3BCRlE',
  'contentDetails': {'videoId': 'ZV5IjNgpBFQ',
   'videoPublishedAt': '2026-03-04T10:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'rgSL6i6bwLtC8-S-Wr2cpStG8eI',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuc0tpMWdFdG5TQVE',
  'contentDetails': {'videoId': 'sKi1gEtnSAQ',
   'videoPublishedAt': '2026-03-04T06:25:03Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'NZebeNbm9JLpHbioN-7wtPJANDA',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEueC1rbDdmekVtYVk',
  'contentDetails': {'videoId': 'x-kl7fzEmaY',
   'videoPublishedAt': '2026-02-28T10:59:59Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'qOx74odQiRmWrm_ryYiLlD98xsI',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuaDFsaTNObFRCMEk',
  'contentDetails': {'videoId': 'h1li3NlTB0I',
   'videoPublishedAt': '2026-02-26T10:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '3iDct6XiSRXqpo7rE6UOXEXCab0',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuT0RvRWFfMWdQU2M',
  'contentDetails': {'videoId': 'ODoEa_1gPSc',
   'videoPublishedAt': '2026-02-20T11:00:04Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'AVfu8c4WUV8UCtq_2sVw-s8lcJk',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuSEZiaXJBRFUzX1E',
  'contentDetails': {'videoId': 'HFbirADU3_Q',
   'videoPublishedAt': '2026-02-19T10:59:57Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '-HuOb07iwIN-mZJnqb8CVnUNhoQ',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuRkVEUTE0dDU4Q0E',
  'contentDetails': {'videoId': 'FEDQ14t58CA',
   'videoPublishedAt': '2026-02-16T02:59:57Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'gkzmJwirQYNo2ZfOv3j1yEo8ob0',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEubVVGS1VKVE1qV2c',
  'contentDetails': {'videoId': 'mUFKUJTMjWg',
   'videoPublishedAt': '2026-02-12T10:59:57Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'n0lPA8WRc7H-MWOIW9vJYaW9pOQ',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuUFVVeEU3RUdQNFE',
  'contentDetails': {'videoId': 'PUUxE7EGP4Q',
   'videoPublishedAt': '2026-02-10T06:25:00Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'm5ralviK1LCbvakF804naK_lfPs',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuT1NVSHFBdnVTUkk',
  'contentDetails': {'videoId': 'OSUHqAvuSRI',
   'videoPublishedAt': '2026-01-31T15:00:00Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'TuRpR4ztXyBCeg632AiS4WrGeaA',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuRjZsZjI2bldrMTA',
  'contentDetails': {'videoId': 'F6lf26nWk10',
   'videoPublishedAt': '2026-01-31T04:00:04Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'jE8qqA1EDBdod6P8bwYr1fPsG5w',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuVHNyM2xCRW45d3c',
  'contentDetails': {'videoId': 'Tsr3lBEn9ww',
   'videoPublishedAt': '2026-01-28T14:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'L_RAwmvjjQTbrwFZjkdZrl9Jd_0',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuSWlxb296Rk9zMXM',
  'contentDetails': {'videoId': 'IiqoozFOs1s',
   'videoPublishedAt': '2026-01-27T10:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'lMviuFdL0nB5R0OQ5ANYJGhSu9Y',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudjF4bTZQY2stbW8',
  'contentDetails': {'videoId': 'v1xm6Pck-mo',
   'videoPublishedAt': '2026-01-21T10:59:59Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'd2NsBQ9yPn60hhRWkb3NPQQwuiQ',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWE9jSDNsZ3cwS0U',
  'contentDetails': {'videoId': 'XOcH3lgw0KE',
   'videoPublishedAt': '2026-01-20T04:00:01Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'Ed-6ZpNG8X9JaLnn4A08UbsXSEo',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuYnBuYWIwQWE1bUU',
  'contentDetails': {'videoId': 'bpnab0Aa5mE',
   'videoPublishedAt': '2026-01-14T11:00:01Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'M3FWucjccljm9mkLJKn5s8z7Q1M',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuZkVUamdZODNvN1E',
  'contentDetails': {'videoId': 'fETjgY83o7Q',
   'videoPublishedAt': '2026-01-12T10:59:56Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'PuSpCr-yS7X6SymZqfiRp91-evQ',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudXJOTFBnYWx0Nm8',
  'contentDetails': {'videoId': 'urNLPgalt6o',
   'videoPublishedAt': '2026-01-07T11:00:03Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'Zx6sGoUhJUPt4qXZqeYnoOK_BB4',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuOWJISmM1SHY5Vnc',
  'contentDetails': {'videoId': '9bHJc5Hv9Vw',
   'videoPublishedAt': '2026-01-05T10:59:56Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'mO2mJFgqm_2Kbe_8R2Nb9Nxo1GE',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuNU9pbzE0NVdCQjg',
  'contentDetails': {'videoId': '5Oio145WBB8',
   'videoPublishedAt': '2025-12-31T15:00:01Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'xxfAsd1vhbuJqNw5EJeH5J_jcGo',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEubnY2V3RObVBYWlU',
  'contentDetails': {'videoId': 'nv6WtNmPXZU',
   'videoPublishedAt': '2025-12-29T11:00:01Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '_pTUjz58TE6gYR4_IQ8Ii4FkG7M',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWXN2Yk42NjVMWkU',
  'contentDetails': {'videoId': 'YsvbN665LZE',
   'videoPublishedAt': '2025-12-27T14:00:00Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'eLDu4cHd3wX6ztgaiOxWcdttZNg',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWmVvSHMyemZYUEU',
  'contentDetails': {'videoId': 'ZeoHs2zfXPE',
   'videoPublishedAt': '2025-12-24T10:59:57Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'pEQ1tGmMog4q27tRFT0ciovlqzo',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEud2dmUGtXU0RVSFU',
  'contentDetails': {'videoId': 'wgfPkWSDUHU',
   'videoPublishedAt': '2025-12-22T10:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'ecxQNLrnPYq7vvyUTMYKw8fLLnQ',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuTUk2X2FIMUpUN3M',
  'contentDetails': {'videoId': 'MI6_aH1JT7s',
   'videoPublishedAt': '2025-12-21T11:59:59Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'h3d2xvJUUAVB6AiqP4rcbGLBuEI',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuSGRncEgzX21aRXM',
  'contentDetails': {'videoId': 'HdgpH3_mZEs',
   'videoPublishedAt': '2025-12-19T10:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '-E_5EREPoGVZAtvsTMwmjspH9HQ',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuZHhpNHBCOWI3ZWc',
  'contentDetails': {'videoId': 'dxi4pB9b7eg',
   'videoPublishedAt': '2025-12-17T10:59:57Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'rEtFtNXkZM1Y9rkpIb5v4Bnkvmw',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudVJKVVZVbFRldk0',
  'contentDetails': {'videoId': 'uRJUVUlTevM',
   'videoPublishedAt': '2025-12-15T10:59:57Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '35urR_kWUXMxYgI6ZRhNpJJEOQg',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuUEVUMzk2TUNJVjg',
  'contentDetails': {'videoId': 'PET396MCIV8',
   'videoPublishedAt': '2025-12-13T10:59:59Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'ug_qHovj1Pki_8KwSkLH0FSq6SM',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuVEE3QzJOQll3ODg',
  'contentDetails': {'videoId': 'TA7C2NBYw88',
   'videoPublishedAt': '2025-12-12T11:00:01Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'OBHNkmjYJKKANOwHuDnNEAH5ICM',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuM3oyN2pPZ1h4LUk',
  'contentDetails': {'videoId': '3z27jOgXx-I',
   'videoPublishedAt': '2025-12-11T10:59:57Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '5QHVOPRZqSId4ffcZ1OFzXp0Jjk',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuNWJ6SGVTcGhnVVU',
  'contentDetails': {'videoId': '5bzHeSphgUU',
   'videoPublishedAt': '2025-12-09T10:59:59Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '52rCCo905c1tsWDD-hsznn_a8nQ',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuWnFuQkNoNTFxVXc',
  'contentDetails': {'videoId': 'ZqnBCh51qUw',
   'videoPublishedAt': '2025-12-08T10:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'vVQXhUwuRMXxgYyQTitB41065so',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuUU5LVFpTWi1YM3M',
  'contentDetails': {'videoId': 'QNKTZSZ-X3s',
   'videoPublishedAt': '2025-12-07T10:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'BEr5rwi9penLrywYnRAH_KB7y88',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuRlI5OU9seE9WdXM',
  'contentDetails': {'videoId': 'FR99OlxOVus',
   'videoPublishedAt': '2025-12-05T11:00:00Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '0CVXEk-c0gdIVE0U-KVydVkXto0',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEueHF1OWVlR1F4WGM',
  'contentDetails': {'videoId': 'xqu9eeGQxXc',
   'videoPublishedAt': '2025-12-04T10:59:58Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '5JlEqyrMA0ZWpK84A6x-TLyI_40',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuN294SlNyTjJDTlE',
  'contentDetails': {'videoId': '7oxJSrN2CNQ',
   'videoPublishedAt': '2025-12-03T10:59:56Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'H-ccgMDOz1biKB3Dwrp3xDFfC60',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudlBQRWZMdjFFcEU',
  'contentDetails': {'videoId': 'vPPEfLv1EpE',
   'videoPublishedAt': '2025-12-02T11:00:00Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': 'uku8YvDSbrCFC0sdNYcqVb5Fe10',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEuazRJc0pEd1JLejQ',
  'contentDetails': {'videoId': 'k4IsJDwRKz4',
   'videoPublishedAt': '2025-12-01T11:00:01Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '2GKegGusnicwwTr1R4RXjtimoew',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEudWRGaWlSNFY2bWc',
  'contentDetails': {'videoId': 'udFiiR4V6mg',
   'videoPublishedAt': '2025-12-01T03:00:03Z'}},
 {'kind': 'youtube#playlistItem',
  'etag': '3hvbaBUmYAxouR5Nc9R-o6uJJZc',
  'id': 'VVVMRjlyTWlFak5hQ1NzZWJzMzFNUkRDUkEud0lKMlRjbkRLUHM',
  'contentDetails': {'videoId': 'wIJ2TcnDKPs',
   'videoPublishedAt': '2025-11-28T11:00:01Z'}}]

In [8]:
response_1["items"][0]["contentDetails"]["videoId"]

'l8sSQAa1kNM'

In [9]:
[item["contentDetails"] for item in response_1["items"]]

[{'videoId': 'l8sSQAa1kNM', 'videoPublishedAt': '2026-03-19T15:00:08Z'},
 {'videoId': '9DSOFyLSv6Q', 'videoPublishedAt': '2026-03-19T10:59:58Z'},
 {'videoId': 'Jl5nNqajrV0', 'videoPublishedAt': '2026-03-18T10:59:56Z'},
 {'videoId': '1tipk2X1aUo', 'videoPublishedAt': '2026-03-17T10:59:56Z'},
 {'videoId': 'bDbzZ_Dx4Ks', 'videoPublishedAt': '2026-03-15T11:00:18Z'},
 {'videoId': 'uB-XPe1K7SU', 'videoPublishedAt': '2026-03-12T10:59:56Z'},
 {'videoId': 'X7jAms_f4Rc', 'videoPublishedAt': '2026-03-10T11:00:03Z'},
 {'videoId': 'bSZL3ZZC8EE', 'videoPublishedAt': '2026-03-07T15:00:00Z'},
 {'videoId': 'o66KJX1YJ3s', 'videoPublishedAt': '2026-03-05T10:59:57Z'},
 {'videoId': 'ZV5IjNgpBFQ', 'videoPublishedAt': '2026-03-04T10:59:58Z'},
 {'videoId': 'sKi1gEtnSAQ', 'videoPublishedAt': '2026-03-04T06:25:03Z'},
 {'videoId': 'x-kl7fzEmaY', 'videoPublishedAt': '2026-02-28T10:59:59Z'},
 {'videoId': 'h1li3NlTB0I', 'videoPublishedAt': '2026-02-26T10:59:58Z'},
 {'videoId': 'ODoEa_1gPSc', 'videoPublishedAt': '2026-02-20T11:00:04Z'},
 {'videoId': 'HFbirADU3_Q', 'videoPublishedAt': '2026-02-19T10:59:57Z'},
 {'videoId': 'FEDQ14t58CA', 'videoPublishedAt': '2026-02-16T02:59:57Z'},
 {'videoId': 'mUFKUJTMjWg', 'videoPublishedAt': '2026-02-12T10:59:57Z'},
 {'videoId': 'PUUxE7EGP4Q', 'videoPublishedAt': '2026-02-10T06:25:00Z'},
 {'videoId': 'OSUHqAvuSRI', 'videoPublishedAt': '2026-01-31T15:00:00Z'},
 {'videoId': 'F6lf26nWk10', 'videoPublishedAt': '2026-01-31T04:00:04Z'},
 {'videoId': 'Tsr3lBEn9ww', 'videoPublishedAt': '2026-01-28T14:59:58Z'},
 {'videoId': 'IiqoozFOs1s', 'videoPublishedAt': '2026-01-27T10:59:58Z'},
 {'videoId': 'v1xm6Pck-mo', 'videoPublishedAt': '2026-01-21T10:59:59Z'},
 {'videoId': 'XOcH3lgw0KE', 'videoPublishedAt': '2026-01-20T04:00:01Z'},
 {'videoId': 'bpnab0Aa5mE', 'videoPublishedAt': '2026-01-14T11:00:01Z'},
 {'videoId': 'fETjgY83o7Q', 'videoPublishedAt': '2026-01-12T10:59:56Z'},
 {'videoId': 'urNLPgalt6o', 'videoPublishedAt': '2026-01-07T11:00:03Z'},
 {'videoId': '9bHJc5Hv9Vw', 'videoPublishedAt': '2026-01-05T10:59:56Z'},
 {'videoId': '5Oio145WBB8', 'videoPublishedAt': '2025-12-31T15:00:01Z'},
 {'videoId': 'nv6WtNmPXZU', 'videoPublishedAt': '2025-12-29T11:00:01Z'},
 {'videoId': 'YsvbN665LZE', 'videoPublishedAt': '2025-12-27T14:00:00Z'},
 {'videoId': 'ZeoHs2zfXPE', 'videoPublishedAt': '2025-12-24T10:59:57Z'},
 {'videoId': 'wgfPkWSDUHU', 'videoPublishedAt': '2025-12-22T10:59:58Z'},
 {'videoId': 'MI6_aH1JT7s', 'videoPublishedAt': '2025-12-21T11:59:59Z'},
 {'videoId': 'HdgpH3_mZEs', 'videoPublishedAt': '2025-12-19T10:59:58Z'},
 {'videoId': 'dxi4pB9b7eg', 'videoPublishedAt': '2025-12-17T10:59:57Z'},
 {'videoId': 'uRJUVUlTevM', 'videoPublishedAt': '2025-12-15T10:59:57Z'},
 {'videoId': 'PET396MCIV8', 'videoPublishedAt': '2025-12-13T10:59:59Z'},
 {'videoId': 'TA7C2NBYw88', 'videoPublishedAt': '2025-12-12T11:00:01Z'},
 {'videoId': '3z27jOgXx-I', 'videoPublishedAt': '2025-12-11T10:59:57Z'},
 {'videoId': '5bzHeSphgUU', 'videoPublishedAt': '2025-12-09T10:59:59Z'},
 {'videoId': 'ZqnBCh51qUw', 'videoPublishedAt': '2025-12-08T10:59:58Z'},
 {'videoId': 'QNKTZSZ-X3s', 'videoPublishedAt': '2025-12-07T10:59:58Z'},
 {'videoId': 'FR99OlxOVus', 'videoPublishedAt': '2025-12-05T11:00:00Z'},
 {'videoId': 'xqu9eeGQxXc', 'videoPublishedAt': '2025-12-04T10:59:58Z'},
 {'videoId': '7oxJSrN2CNQ', 'videoPublishedAt': '2025-12-03T10:59:56Z'},
 {'videoId': 'vPPEfLv1EpE', 'videoPublishedAt': '2025-12-02T11:00:00Z'},
 {'videoId': 'k4IsJDwRKz4', 'videoPublishedAt': '2025-12-01T11:00:01Z'},
 {'videoId': 'udFiiR4V6mg', 'videoPublishedAt': '2025-12-01T03:00:03Z'},
 {'videoId': 'wIJ2TcnDKPs', 'videoPublishedAt': '2025-11-28T11:00:01Z'}]

In [10]:
# Append the first 50 video IDs to video_ids
vid_ids_1 = [item["contentDetails"]["videoId"] for item in response_1["items"]]
video_ids.extend(vid_ids_1)
display(video_ids)

['l8sSQAa1kNM',
 '9DSOFyLSv6Q',
 'Jl5nNqajrV0',
 '1tipk2X1aUo',
 'bDbzZ_Dx4Ks',
 'uB-XPe1K7SU',
 'X7jAms_f4Rc',
 'bSZL3ZZC8EE',
 'o66KJX1YJ3s',
 'ZV5IjNgpBFQ',
 'sKi1gEtnSAQ',
 'x-kl7fzEmaY',
 'h1li3NlTB0I',
 'ODoEa_1gPSc',
 'HFbirADU3_Q',
 'FEDQ14t58CA',
 'mUFKUJTMjWg',
 'PUUxE7EGP4Q',
 'OSUHqAvuSRI',
 'F6lf26nWk10',
 'Tsr3lBEn9ww',
 'IiqoozFOs1s',
 'v1xm6Pck-mo',
 'XOcH3lgw0KE',
 'bpnab0Aa5mE',
 'fETjgY83o7Q',
 'urNLPgalt6o',
 '9bHJc5Hv9Vw',
 '5Oio145WBB8',
 'nv6WtNmPXZU',
 'YsvbN665LZE',
 'ZeoHs2zfXPE',
 'wgfPkWSDUHU',
 'MI6_aH1JT7s',
 'HdgpH3_mZEs',
 'dxi4pB9b7eg',
 'uRJUVUlTevM',
 'PET396MCIV8',
 'TA7C2NBYw88',
 '3z27jOgXx-I',
 '5bzHeSphgUU',
 'ZqnBCh51qUw',
 'QNKTZSZ-X3s',
 'FR99OlxOVus',
 'xqu9eeGQxXc',
 '7oxJSrN2CNQ',
 'vPPEfLv1EpE',
 'k4IsJDwRKz4',
 'udFiiR4V6mg',
 'wIJ2TcnDKPs']

In [11]:
# Fetch the last 50 longform video IDs
next_page_token = response_1.get("nextPageToken")

response_2 = youtube.playlistItems().list(
    part="contentDetails",
    playlistId=longform_playlist_id,
    maxResults=50,
    pageToken=next_page_token
).execute()

vid_ids_2 = [item["contentDetails"]["videoId"] for item in response_2["items"]]
video_ids.extend(vid_ids_2)

In [12]:
# Total of the video IDs collected so far
len(video_ids)

100

In [15]:
video_ids[0:2]

['l8sSQAa1kNM', '9DSOFyLSv6Q']

In [11]:
all_current_videos = []
video_format = "Long-form"

for vid in video_ids:
    all_current_videos.append({"id": vid, "format": video_format})

In [12]:
all_current_videos

[{'id': 'l8sSQAa1kNM', 'format': 'Long-form'},
 {'id': '9DSOFyLSv6Q', 'format': 'Long-form'},
 {'id': 'Jl5nNqajrV0', 'format': 'Long-form'},
 {'id': '1tipk2X1aUo', 'format': 'Long-form'},
 {'id': 'bDbzZ_Dx4Ks', 'format': 'Long-form'},
 {'id': 'uB-XPe1K7SU', 'format': 'Long-form'},
 {'id': 'X7jAms_f4Rc', 'format': 'Long-form'},
 {'id': 'bSZL3ZZC8EE', 'format': 'Long-form'},
 {'id': 'o66KJX1YJ3s', 'format': 'Long-form'},
 {'id': 'ZV5IjNgpBFQ', 'format': 'Long-form'},
 {'id': 'sKi1gEtnSAQ', 'format': 'Long-form'},
 {'id': 'x-kl7fzEmaY', 'format': 'Long-form'},
 {'id': 'h1li3NlTB0I', 'format': 'Long-form'},
 {'id': 'ODoEa_1gPSc', 'format': 'Long-form'},
 {'id': 'HFbirADU3_Q', 'format': 'Long-form'},
 {'id': 'FEDQ14t58CA', 'format': 'Long-form'},
 {'id': 'mUFKUJTMjWg', 'format': 'Long-form'},
 {'id': 'PUUxE7EGP4Q', 'format': 'Long-form'},
 {'id': 'OSUHqAvuSRI', 'format': 'Long-form'},
 {'id': 'F6lf26nWk10', 'format': 'Long-form'},
 {'id': 'Tsr3lBEn9ww', 'format': 'Long-form'},
 {'id': 'IiqoozFOs1s', 'format': 'Long-form'},
 {'id': 'v1xm6Pck-mo', 'format': 'Long-form'},
 {'id': 'XOcH3lgw0KE', 'format': 'Long-form'},
 {'id': 'bpnab0Aa5mE', 'format': 'Long-form'},
 {'id': 'fETjgY83o7Q', 'format': 'Long-form'},
 {'id': 'urNLPgalt6o', 'format': 'Long-form'},
 {'id': '9bHJc5Hv9Vw', 'format': 'Long-form'},
 {'id': '5Oio145WBB8', 'format': 'Long-form'},
 {'id': 'nv6WtNmPXZU', 'format': 'Long-form'},
 {'id': 'YsvbN665LZE', 'format': 'Long-form'},
 {'id': 'ZeoHs2zfXPE', 'format': 'Long-form'},
 {'id': 'wgfPkWSDUHU', 'format': 'Long-form'},
 {'id': 'MI6_aH1JT7s', 'format': 'Long-form'},
 {'id': 'HdgpH3_mZEs', 'format': 'Long-form'},
 {'id': 'dxi4pB9b7eg', 'format': 'Long-form'},
 {'id': 'uRJUVUlTevM', 'format': 'Long-form'},
 {'id': 'PET396MCIV8', 'format': 'Long-form'},
 {'id': 'TA7C2NBYw88', 'format': 'Long-form'},
 {'id': '3z27jOgXx-I', 'format': 'Long-form'},
 {'id': '5bzHeSphgUU', 'format': 'Long-form'},
 {'id': 'ZqnBCh51qUw', 'format': 'Long-form'},
 {'id': 'QNKTZSZ-X3s', 'format': 'Long-form'},
 {'id': 'FR99OlxOVus', 'format': 'Long-form'},
 {'id': 'xqu9eeGQxXc', 'format': 'Long-form'},
 {'id': '7oxJSrN2CNQ', 'format': 'Long-form'},
 {'id': 'vPPEfLv1EpE', 'format': 'Long-form'},
 {'id': 'k4IsJDwRKz4', 'format': 'Long-form'},
 {'id': 'udFiiR4V6mg', 'format': 'Long-form'},
 {'id': 'wIJ2TcnDKPs', 'format': 'Long-form'},
 {'id': 'FCXd9nXSWTM', 'format': 'Long-form'},
 {'id': 'mf967jPZrCk', 'format': 'Long-form'},
 {'id': 'eHmQ_b0LkUA', 'format': 'Long-form'},
 {'id': 'FECQ9MmbC4Y', 'format': 'Long-form'},
 {'id': 'kaBPTrvzf8c', 'format': 'Long-form'},
 {'id': 'ZSy5AcukDjI', 'format': 'Long-form'},
 {'id': 'FnWKcU7ayH0', 'format': 'Long-form'},
 {'id': 'Hw4Qwy_Kr-8', 'format': 'Long-form'},
 {'id': 'XZL0Dvxs7jY', 'format': 'Long-form'},
 {'id': 'Csaxd97bVJE', 'format': 'Long-form'},
 {'id': '1ydl2uTMPGo', 'format': 'Long-form'},
 {'id': 'U9-7JBGRyMc', 'format': 'Long-form'},
 {'id': 'IUreR3zoD3s', 'format': 'Long-form'},
 {'id': 'pPfpE6pOapA', 'format': 'Long-form'},
 {'id': 'XU08DOMg2EY', 'format': 'Long-form'},
 {'id': 'RJvYHFKknfM', 'format': 'Long-form'},
 {'id': 'w9eOsEFpM6A', 'format': 'Long-form'},
 {'id': 'V77feEklVzA', 'format': 'Long-form'},
 {'id': 'y7z55mObLO8', 'format': 'Long-form'},
 {'id': '2kQENtCRu6Y', 'format': 'Long-form'},
 {'id': 'i2FGGGhHduE', 'format': 'Long-form'},
 {'id': '0oTtNyRhpm8', 'format': 'Long-form'},
 {'id': 't3QYengDjr0', 'format': 'Long-form'},
 {'id': 'ECC-hru050A', 'format': 'Long-form'},
 {'id': '9gerQFZUXjc', 'format': 'Long-form'},
 {'id': 'iip2qL9cB7Q', 'format': 'Long-form'},
 {'id': '1EP5hxH6O7M', 'format': 'Long-form'},
 {'id': 'dLgCTUvBdkU', 'format': 'Long-form'},
 {'id': 'pVNEUDePkSk', 'format': 'Long-form'},
 {'id': 'i6ywIzsx1NI', 'format': 'Long-form'},
 {'id': 'krVcQgnK3EU', 'format': 'Long-form'},
 {'id': 'Y1mYx1pJVHk', 'format': 'Long-form'},
 {'id': '2c6V6rC-dXg', 'format': 'Long-form'},
 {'id': 'lT2OKzBpqQA', 'format': 'Long-form'},
 {'id': '0e68vNHgIkk', 'format': 'Long-form'},
 {'id': 'kuSUU0oe1J0', 'format': 'Long-form'},
 {'id': '_YOUhOuFNs4', 'format': 'Long-form'},
 {'id': '70wchLxP4io', 'format': 'Long-form'},
 {'id': 'cc7f4fX1ORA', 'format': 'Long-form'},
 {'id': 'CUX4XYIW6gw', 'format': 'Long-form'},
 {'id': 'zMJhEXR7meQ', 'format': 'Long-form'},
 {'id': 'eMki9Cw_m-I', 'format': 'Long-form'},
 {'id': 'iP6Ubt6Z-XM', 'format': 'Long-form'},
 {'id': 'yL2Dt8wjgJQ', 'format': 'Long-form'},
 {'id': 'r-qO8McDYgE', 'format': 'Long-form'},
 {'id': 'BR_7CF8v744', 'format': 'Long-form'},
 {'id': '8-PUkLkCDW8', 'format': 'Long-form'},
 {'id': 'y-rPpGpnSg0', 'format': 'Long-form'},
 {'id': 'cW9D6_g6MR0', 'format': 'Long-form'},
 {'id': 'ciRftriyejM', 'format': 'Long-form'}]

# Fetching Video Metadata & Stats

In [20]:
# Batch Process Videos for Stats & Metadata (2 at a time)
chunk_size = 2

batch = all_current_videos[0: 0 + chunk_size]
display(batch)
batch_ids = [v["id"] for v in batch]
display(batch_ids)
batch_formats = {v["id"]: v["format"] for v in batch}
display(batch_formats)

[{'id': 'l8sSQAa1kNM', 'format': 'Long-form'},
 {'id': '9DSOFyLSv6Q', 'format': 'Long-form'}]

['l8sSQAa1kNM', '9DSOFyLSv6Q']

{'l8sSQAa1kNM': 'Long-form', '9DSOFyLSv6Q': 'Long-form'}

In [24]:
",".join(batch_ids)

'l8sSQAa1kNM,9DSOFyLSv6Q'

In [ ]:
# Extract Stats for Two Videos
vid_response = youtube.videos().list(
    part="snippet,statistics",
    id=batch_ids
).execute()
display(vid_response)

{'kind': 'youtube#videoListResponse',
 'etag': 'qFaiM4CH5faIvtUtVOYQ0G20VWw',
 'items': [{'kind': 'youtube#video',
   'etag': 'kYeYLcSnn9SLwyAGyLX3wCEiGmk',
   'id': 'l8sSQAa1kNM',
   'snippet': {'publishedAt': '2026-03-19T15:00:08Z',
    'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
    'title': 'Hyunjin "LOVER" Video',
    'description': '현진(Hyunjin) "LOVER" Video\n\n[Credits]\nLyrics by : 현진\nComposed by : 현진, joha\nArranged by : joha\nOriginal Publisher : JYP Entertainment, Copyright Control\n\n[Hyunjin "LOVER" Lyrics]\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한 때 사랑하긴 했던 거지? Right, right?\n\nLover lover lover is hurt ’cause she went away \nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n \n오 맨정신은 벅차\nI don’t want to drink no more no more no more\nWhy’re you acting like it’s me \nIt’s all my fault, you mean?\n하긴 원래 넌 그런 애였을 테니\n \nWhy why is it not me\nIn your eyes 이유를 찾지 ooh ooh ooh ooh\n\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한때 사랑하긴 했던 거지? Right, right?\n \nLover lover lover is hurt ’cause she went away\nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what i say\n\nLover lover lover needs a hug cause she‘s gone away\nLoved her loved her loved her so much 미화된 기억엔\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\n이젠 널 놓아도 돼?\n우린 알잖아 솔직히 첫 단추가 어긋\n첨의 그 설렘, 약속했던 것 \n누구도 되돌리지 못하는 기억들\n\nTell me why 어떤 게 그리도 맘에 걸려서\nTell me how 어떤 식으로 했어야만 했어\nTell me why 어떻게 그리 쉽게도 변해서\nTell me how to get out of this \nNow I’m done with you\n\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한때 사랑하긴 했던 거지? Right, right?\n \nLover lover lover is hurt ’cause she went away\nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\nLover lover lover needs a hug ’cause she‘s gone away\nLoved her loved her loved her so much 미화된 기억엔\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\nListen to "DO IT" now☁️\nhttps://Stray-Kids.lnk.to/DOIT\n\nListen to "Do It (Remixes)" now🎊\nhttps://Stray-Kids.lnk.to/DoItRemixes\n\nStray Kids "DO IT"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DOIT/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DOIT/Spotify\n\nStray Kids "Do It (Remixes)"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DoItRemixes/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DoItRemixes/Spotify\n\nStray Kids Official YouTube: https://www.youtube.com/c/StrayKids\nStray Kids Official Twitter: https://twitter.com/Stray_Kids\nStray Kids Official Instagram: https://www.instagram.com/realstraykids/\nStray Kids Official TikTok: https://www.tiktok.com/@jypestraykids\nStray Kids Official Facebook: https://www.facebook.com/JYPEStrayKids/\nStray Kids Official Threads: https://www.threads.com/@realstraykids\nStray Kids Official FANS (Android) https://play.google.com/store/apps/details?id=com.jype.fans\nStray Kids Official FANS (iOS) https://apps.apple.com/app/fans-for-fans-artists/id6474999628\n\n#StrayKids #스트레이키즈\n#현진 #Hyunjin\n#YouMakeStrayKidsStay\n\nCopyrights 2026 ⓒ JYP Entertainment. All Rights Reserved.',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'Stray Kids',
    'tags': ['JYP Entertainment',
     'JYP',
     'Stray Kids',
     '스트레이 키즈',
     'SKZ',
     '스키즈',
     '방찬',
     'BANG CHAN',
     '리노',
     'LEE KNOW',
     '창빈',
     'CHANGBIN',
     '현진',
     '황현진',
     'HYUNJIN',
     '한',
     '한지성',
     'HAN',
     '필릭스',
     'FELIX',
     '용복',
     '승민',
     '김승민',
     'SEUNGMIN',
     '아이엔',
     'I.N',
     '현진 러버',
     '러버',
     'LOVER',
     'Hyunjin LOVER',
     '현진 LOVER',
     '스트레이 키즈 현진 러버',
     '스키즈 현진 러버',
     'SKZ Hyunjin LOVER',
     'Stray Kids Hyunjin LOVER',
     '황현진 러버',
     '황현진 LOVER',
     '현진 작사',
     '현진 작곡',
     '스키즈 현진 작사',
     '스키즈 현진 작곡',
     'Hyunjin vocal',
     '현진 보컬',
     '현진 노래',
     '스키즈 자작곡',
     '스트레이키즈 자작곡',
     '황현진 작사',
     '황현진 작곡',
     '황현진 보컬',
     '현진 자작곡',
     '스키즈 현진 자작곡',
     '스트레이 키즈 현진 자작곡',
     'Hyunjin song'],
    'categoryId': '10',
    'liveBroadcastContent': 'none',
    'defaultLanguage': 'en',
    'localized': {'title': 'Hyunjin "LOVER" Video',
     'description': '현진(Hyunjin) "LOVER" Video\n\n[Credits]\nLyrics by : 현진\nComposed by : 현진, joha\nArranged by : joha\nOriginal Publisher : JYP Entertainment, Copyright Control\n\n[Hyunjin "LOVER" Lyrics]\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한 때 사랑하긴 했던 거지? Right, right?\n\nLover lover lover is hurt ’cause she went away \nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n \n오 맨정신은 벅차\nI don’t want to drink no more no more no more\nWhy’re you acting like it’s me \nIt’s all my fault, you mean?\n하긴 원래 넌 그런 애였을 테니\n \nWhy why is it not me\nIn your eyes 이유를 찾지 ooh ooh ooh ooh\n\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한때 사랑하긴 했던 거지? Right, right?\n \nLover lover lover is hurt ’cause she went away\nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what i say\n\nLover lover lover needs a hug cause she‘s gone away\nLoved her loved her loved her so much 미화된 기억엔\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\n이젠 널 놓아도 돼?\n우린 알잖아 솔직히 첫 단추가 어긋\n첨의 그 설렘, 약속했던 것 \n누구도 되돌리지 못하는 기억들\n\nTell me why 어떤 게 그리도 맘에 걸려서\nTell me how 어떤 식으로 했어야만 했어\nTell me why 어떻게 그리 쉽게도 변해서\nTell me how to get out of this \nNow I’m done with you\n\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한때 사랑하긴 했던 거지? Right, right?\n \nLover lover lover is hurt ’cause she went away\nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\nLover lover lover needs a hug ’cause she‘s gone away\nLoved her loved her loved her so much 미화된 기억엔\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\nListen to "DO IT" now☁️\nhttps://Stray-Kids.lnk.to/DOIT\n\nListen to "Do It (Remixes)" now🎊\nhttps://Stray-Kids.lnk.to/DoItRemixes\n\nStray Kids "DO IT"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DOIT/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DOIT/Spotify\n\nStray Kids "Do It (Remixes)"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DoItRemixes/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DoItRemixes/Spotify\n\nStray Kids Official YouTube: https://www.youtube.com/c/StrayKids\nStray Kids Official Twitter: https://twitter.com/Stray_Kids\nStray Kids Official Instagram: https://www.instagram.com/realstraykids/\nStray Kids Official TikTok: https://www.tiktok.com/@jypestraykids\nStray Kids Official Facebook: https://www.facebook.com/JYPEStrayKids/\nStray Kids Official Threads: https://www.threads.com/@realstraykids\nStray Kids Official FANS (Android) https://play.google.com/store/apps/details?id=com.jype.fans\nStray Kids Official FANS (iOS) https://apps.apple.com/app/fans-for-fans-artists/id6474999628\n\n#StrayKids #스트레이키즈\n#현진 #Hyunjin\n#YouMakeStrayKidsStay\n\nCopyrights 2026 ⓒ JYP Entertainment. All Rights Reserved.'},
    'defaultAudioLanguage': 'ko'},
   'statistics': {'viewCount': '5628876',
    'likeCount': '705144',
    'favoriteCount': '0',
    'commentCount': '53486'}},
  {'kind': 'youtube#video',
   'etag': 'hZnX-8X9m4IilVs0Ay9Oqh6wnlw',
   'id': '9DSOFyLSv6Q',
   'snippet': {'publishedAt': '2026-03-19T10:59:58Z',
    'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
    'title': '스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE] Ep.94',
    'description': '스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE(스키즈 코드)] Ep.94\n\n✨ English, Japanese, Chinese, Spanish, Indonesian & Thai subtitles are available!\n\nListen to "DO IT" now☁️\nhttps://Stray-Kids.lnk.to/DOIT\n\nListen to "Do It (Remixes)" now🎊\nhttps://Stray-Kids.lnk.to/DoItRemixes\n\nStray Kids "DO IT"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DOIT/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DOIT/Spotify\n\nStray Kids "Do It (Remixes)"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DoItRemixes/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DoItRemixes/Spotify\n\nStray Kids Official YouTube: https://www.youtube.com/c/StrayKids\nStray Kids Official Twitter: https://twitter.com/Stray_Kids\nStray Kids Official Instagram: https://www.instagram.com/realstraykids/\nStray Kids Official TikTok: https://www.tiktok.com/@jypestraykids\nStray Kids Official Facebook: https://www.facebook.com/JYPEStrayKids/\nStray Kids Official Threads: https://www.threads.com/@realstraykids\nStray Kids Official FANS (Android) https://play.google.com/store/apps/details?id=com.jype.fans\nStray Kids Official FANS (iOS) https://apps.apple.com/app/fans-for-fans-artists/id6474999628\n\n#StrayKids #스트레이키즈\n#스키즈코드 #SKZCODE\n#스키즈문화센터\n#SKZCommunityCenter\n#YouMakeStrayKidsStay\n\nCopyrights 2026 ⓒ JYP Entertainment. All Rights Reserved.',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'Stray Kids',
    'tags': ['Stray Kids',
     '스트레이 키즈',
     'SKZ',
     '스키즈',
     '방찬',
     'BANG CHAN',
     '리노',
     '이민호',
     'LEE KNOW',
     '창빈',
     '서창빈',
     'CHANGBIN',
     '현진',
     '황현진',
     'HYUNJIN',
     'HWANGHYUNJIN',
     '한',
     '지성',
     '한지성',
     'HAN',
     'HANJISUNG',
     '필릭스',
     'FELIX',
     '용복',
     '이용복',
     '승민',
     '김승민',
     'SEUNGMIN',
     '아이엔',
     '양정인',
     'I.N',
     'YANGJEONGIN',
     '스키즈 자체콘텐츠',
     '스키즈 자컨',
     '슼즈코드',
     'skz code',
     '스키즈 리얼리티',
     '스트레이키즈 리얼리티',
     '스트레이키즈 예능',
     '스키즈 예능',
     'skz reality',
     '스키즈 게임',
     'skz game',
     '스키즈 아기',
     '스키즈 육아',
     '스키즈코드 아기',
     '스키즈코드 육아',
     'skz baby',
     '스키즈 아기 돌보기',
     '스키즈코드 문화센터',
     '스키즈 구연동화',
     '스키즈 육아 예능',
     'skz code community center',
     '스키즈코드 아기 돌보기'],
    'categoryId': '10',
    'liveBroadcastContent': 'none',
    'defaultLanguage': 'en',
    'localized': {'title': '스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE] Ep.94',
     'description': '스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE(스키즈 코드)] Ep.94\n\n✨ English, Japanese, Chinese, Spanish, Indonesian & Thai subtitles are available!\n\nListen to "DO IT" now☁️\nhttps://Stray-Kids.lnk.to/DOIT\n\nListen to "Do It (Remixes)" now🎊\nhttps://Stray-Kids.lnk.to/DoItRemixes\n\nStray Kids "DO IT"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DOIT/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DOIT/Spotify\n\nStray Kids "Do It (Remixes)"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DoItRemixes/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DoItRemixes/Spotify\n\nStray Kids Official YouTube: https://www.youtube.com/c/StrayKids\nStray Kids Official Twitter: https://twitter.com/Stray_Kids\nStray Kids Official Instagram: https://www.instagram.com/realstraykids/\nStray Kids Official TikTok: https://www.tiktok.com/@jypestraykids\nStray Kids Official Facebook: https://www.facebook.com/JYPEStrayKids/\nStray Kids Official Threads: https://www.threads.com/@realstraykids\nStray Kids Official FANS (Android) https://play.google.com/store/apps/details?id=com.jype.fans\nStray Kids Official FANS (iOS) https://apps.apple.com/app/fans-for-fans-artists/id6474999628\n\n#StrayKids #스트레이키즈\n#스키즈코드 #SKZCODE\n#스키즈문화센터\n#SKZCommunityCenter\n#YouMakeStrayKidsStay\n\nCopyrights 2026 ⓒ JYP Entertainment. All Rights Reserved.'},
    'defaultAudioLanguage': 'ko'},
   'statistics': {'viewCount': '1979744',
    'likeCount': '185618',
    'favoriteCount': '0',
    'commentCount': '7034'}}],
 'pageInfo': {'totalResults': 2, 'resultsPerPage': 2}}

In [17]:
type(vid_response['items'])

list

In [22]:
vid_response['items'][0]

{'kind': 'youtube#video',
 'etag': 'kYeYLcSnn9SLwyAGyLX3wCEiGmk',
 'id': 'l8sSQAa1kNM',
 'snippet': {'publishedAt': '2026-03-19T15:00:08Z',
  'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
  'title': 'Hyunjin "LOVER" Video',
  'description': '현진(Hyunjin) "LOVER" Video\n\n[Credits]\nLyrics by : 현진\nComposed by : 현진, joha\nArranged by : joha\nOriginal Publisher : JYP Entertainment, Copyright Control\n\n[Hyunjin "LOVER" Lyrics]\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한 때 사랑하긴 했던 거지? Right, right?\n\nLover lover lover is hurt ’cause she went away \nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n \n오 맨정신은 벅차\nI don’t want to drink no more no more no more\nWhy’re you acting like it’s me \nIt’s all my fault, you mean?\n하긴 원래 넌 그런 애였을 테니\n \nWhy why is it not me\nIn your eyes 이유를 찾지 ooh ooh ooh ooh\n\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한때 사랑하긴 했던 거지? Right, right?\n \nLover lover lover is hurt ’cause she went away\nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what i say\n\nLover lover lover needs a hug cause she‘s gone away\nLoved her loved her loved her so much 미화된 기억엔\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\n이젠 널 놓아도 돼?\n우린 알잖아 솔직히 첫 단추가 어긋\n첨의 그 설렘, 약속했던 것 \n누구도 되돌리지 못하는 기억들\n\nTell me why 어떤 게 그리도 맘에 걸려서\nTell me how 어떤 식으로 했어야만 했어\nTell me why 어떻게 그리 쉽게도 변해서\nTell me how to get out of this \nNow I’m done with you\n\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한때 사랑하긴 했던 거지? Right, right?\n \nLover lover lover is hurt ’cause she went away\nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\nLover lover lover needs a hug ’cause she‘s gone away\nLoved her loved her loved her so much 미화된 기억엔\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\nListen to "DO IT" now☁️\nhttps://Stray-Kids.lnk.to/DOIT\n\nListen to "Do It (Remixes)" now🎊\nhttps://Stray-Kids.lnk.to/DoItRemixes\n\nStray Kids "DO IT"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DOIT/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DOIT/Spotify\n\nStray Kids "Do It (Remixes)"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DoItRemixes/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DoItRemixes/Spotify\n\nStray Kids Official YouTube: https://www.youtube.com/c/StrayKids\nStray Kids Official Twitter: https://twitter.com/Stray_Kids\nStray Kids Official Instagram: https://www.instagram.com/realstraykids/\nStray Kids Official TikTok: https://www.tiktok.com/@jypestraykids\nStray Kids Official Facebook: https://www.facebook.com/JYPEStrayKids/\nStray Kids Official Threads: https://www.threads.com/@realstraykids\nStray Kids Official FANS (Android) https://play.google.com/store/apps/details?id=com.jype.fans\nStray Kids Official FANS (iOS) https://apps.apple.com/app/fans-for-fans-artists/id6474999628\n\n#StrayKids #스트레이키즈\n#현진 #Hyunjin\n#YouMakeStrayKidsStay\n\nCopyrights 2026 ⓒ JYP Entertainment. All Rights Reserved.',
  'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/default.jpg',
    'width': 120,
    'height': 90},
   'medium': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/mqdefault.jpg',
    'width': 320,
    'height': 180},
   'high': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/hqdefault.jpg',
    'width': 480,
    'height': 360},
   'standard': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/sddefault.jpg',
    'width': 640,
    'height': 480},
   'maxres': {'url': 'https://i.ytimg.com/vi/l8sSQAa1kNM/maxresdefault.jpg',
    'width': 1280,
    'height': 720}},
  'channelTitle': 'Stray Kids',
  'tags': ['JYP Entertainment',
   'JYP',
   'Stray Kids',
   '스트레이 키즈',
   'SKZ',
   '스키즈',
   '방찬',
   'BANG CHAN',
   '리노',
   'LEE KNOW',
   '창빈',
   'CHANGBIN',
   '현진',
   '황현진',
   'HYUNJIN',
   '한',
   '한지성',
   'HAN',
   '필릭스',
   'FELIX',
   '용복',
   '승민',
   '김승민',
   'SEUNGMIN',
   '아이엔',
   'I.N',
   '현진 러버',
   '러버',
   'LOVER',
   'Hyunjin LOVER',
   '현진 LOVER',
   '스트레이 키즈 현진 러버',
   '스키즈 현진 러버',
   'SKZ Hyunjin LOVER',
   'Stray Kids Hyunjin LOVER',
   '황현진 러버',
   '황현진 LOVER',
   '현진 작사',
   '현진 작곡',
   '스키즈 현진 작사',
   '스키즈 현진 작곡',
   'Hyunjin vocal',
   '현진 보컬',
   '현진 노래',
   '스키즈 자작곡',
   '스트레이키즈 자작곡',
   '황현진 작사',
   '황현진 작곡',
   '황현진 보컬',
   '현진 자작곡',
   '스키즈 현진 자작곡',
   '스트레이 키즈 현진 자작곡',
   'Hyunjin song'],
  'categoryId': '10',
  'liveBroadcastContent': 'none',
  'defaultLanguage': 'en',
  'localized': {'title': 'Hyunjin "LOVER" Video',
   'description': '현진(Hyunjin) "LOVER" Video\n\n[Credits]\nLyrics by : 현진\nComposed by : 현진, joha\nArranged by : joha\nOriginal Publisher : JYP Entertainment, Copyright Control\n\n[Hyunjin "LOVER" Lyrics]\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한 때 사랑하긴 했던 거지? Right, right?\n\nLover lover lover is hurt ’cause she went away \nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n \n오 맨정신은 벅차\nI don’t want to drink no more no more no more\nWhy’re you acting like it’s me \nIt’s all my fault, you mean?\n하긴 원래 넌 그런 애였을 테니\n \nWhy why is it not me\nIn your eyes 이유를 찾지 ooh ooh ooh ooh\n\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한때 사랑하긴 했던 거지? Right, right?\n \nLover lover lover is hurt ’cause she went away\nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what i say\n\nLover lover lover needs a hug cause she‘s gone away\nLoved her loved her loved her so much 미화된 기억엔\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\n이젠 널 놓아도 돼?\n우린 알잖아 솔직히 첫 단추가 어긋\n첨의 그 설렘, 약속했던 것 \n누구도 되돌리지 못하는 기억들\n\nTell me why 어떤 게 그리도 맘에 걸려서\nTell me how 어떤 식으로 했어야만 했어\nTell me why 어떻게 그리 쉽게도 변해서\nTell me how to get out of this \nNow I’m done with you\n\nYeah yeah yeah yeah\nI’m running in the rain yeah\n망가진 내 맘 씻겨 내리길\n한때 사랑하긴 했던 거지? Right, right?\n \nLover lover lover is hurt ’cause she went away\nLoved her loved her loved her so much until that rainy day\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\nLover lover lover needs a hug ’cause she‘s gone away\nLoved her loved her loved her so much 미화된 기억엔\nLover lover lover dies ’cause there’s no way\nLover lover love is gone no matter what I say\n\nListen to "DO IT" now☁️\nhttps://Stray-Kids.lnk.to/DOIT\n\nListen to "Do It (Remixes)" now🎊\nhttps://Stray-Kids.lnk.to/DoItRemixes\n\nStray Kids "DO IT"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DOIT/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DOIT/Spotify\n\nStray Kids "Do It (Remixes)"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DoItRemixes/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DoItRemixes/Spotify\n\nStray Kids Official YouTube: https://www.youtube.com/c/StrayKids\nStray Kids Official Twitter: https://twitter.com/Stray_Kids\nStray Kids Official Instagram: https://www.instagram.com/realstraykids/\nStray Kids Official TikTok: https://www.tiktok.com/@jypestraykids\nStray Kids Official Facebook: https://www.facebook.com/JYPEStrayKids/\nStray Kids Official Threads: https://www.threads.com/@realstraykids\nStray Kids Official FANS (Android) https://play.google.com/store/apps/details?id=com.jype.fans\nStray Kids Official FANS (iOS) https://apps.apple.com/app/fans-for-fans-artists/id6474999628\n\n#StrayKids #스트레이키즈\n#현진 #Hyunjin\n#YouMakeStrayKidsStay\n\nCopyrights 2026 ⓒ JYP Entertainment. All Rights Reserved.'},
  'defaultAudioLanguage': 'ko'},
 'statistics': {'viewCount': '5628876',
  'likeCount': '705144',
  'favoriteCount': '0',
  'commentCount': '53486'}}

In [21]:
vid_response['items'][1]

{'kind': 'youtube#video',
 'etag': 'hZnX-8X9m4IilVs0Ay9Oqh6wnlw',
 'id': '9DSOFyLSv6Q',
 'snippet': {'publishedAt': '2026-03-19T10:59:58Z',
  'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
  'title': '스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE] Ep.94',
  'description': '스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE(스키즈 코드)] Ep.94\n\n✨ English, Japanese, Chinese, Spanish, Indonesian & Thai subtitles are available!\n\nListen to "DO IT" now☁️\nhttps://Stray-Kids.lnk.to/DOIT\n\nListen to "Do It (Remixes)" now🎊\nhttps://Stray-Kids.lnk.to/DoItRemixes\n\nStray Kids "DO IT"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DOIT/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DOIT/Spotify\n\nStray Kids "Do It (Remixes)"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DoItRemixes/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DoItRemixes/Spotify\n\nStray Kids Official YouTube: https://www.youtube.com/c/StrayKids\nStray Kids Official Twitter: https://twitter.com/Stray_Kids\nStray Kids Official Instagram: https://www.instagram.com/realstraykids/\nStray Kids Official TikTok: https://www.tiktok.com/@jypestraykids\nStray Kids Official Facebook: https://www.facebook.com/JYPEStrayKids/\nStray Kids Official Threads: https://www.threads.com/@realstraykids\nStray Kids Official FANS (Android) https://play.google.com/store/apps/details?id=com.jype.fans\nStray Kids Official FANS (iOS) https://apps.apple.com/app/fans-for-fans-artists/id6474999628\n\n#StrayKids #스트레이키즈\n#스키즈코드 #SKZCODE\n#스키즈문화센터\n#SKZCommunityCenter\n#YouMakeStrayKidsStay\n\nCopyrights 2026 ⓒ JYP Entertainment. All Rights Reserved.',
  'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/default.jpg',
    'width': 120,
    'height': 90},
   'medium': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/mqdefault.jpg',
    'width': 320,
    'height': 180},
   'high': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/hqdefault.jpg',
    'width': 480,
    'height': 360},
   'standard': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/sddefault.jpg',
    'width': 640,
    'height': 480},
   'maxres': {'url': 'https://i.ytimg.com/vi/9DSOFyLSv6Q/maxresdefault.jpg',
    'width': 1280,
    'height': 720}},
  'channelTitle': 'Stray Kids',
  'tags': ['Stray Kids',
   '스트레이 키즈',
   'SKZ',
   '스키즈',
   '방찬',
   'BANG CHAN',
   '리노',
   '이민호',
   'LEE KNOW',
   '창빈',
   '서창빈',
   'CHANGBIN',
   '현진',
   '황현진',
   'HYUNJIN',
   'HWANGHYUNJIN',
   '한',
   '지성',
   '한지성',
   'HAN',
   'HANJISUNG',
   '필릭스',
   'FELIX',
   '용복',
   '이용복',
   '승민',
   '김승민',
   'SEUNGMIN',
   '아이엔',
   '양정인',
   'I.N',
   'YANGJEONGIN',
   '스키즈 자체콘텐츠',
   '스키즈 자컨',
   '슼즈코드',
   'skz code',
   '스키즈 리얼리티',
   '스트레이키즈 리얼리티',
   '스트레이키즈 예능',
   '스키즈 예능',
   'skz reality',
   '스키즈 게임',
   'skz game',
   '스키즈 아기',
   '스키즈 육아',
   '스키즈코드 아기',
   '스키즈코드 육아',
   'skz baby',
   '스키즈 아기 돌보기',
   '스키즈코드 문화센터',
   '스키즈 구연동화',
   '스키즈 육아 예능',
   'skz code community center',
   '스키즈코드 아기 돌보기'],
  'categoryId': '10',
  'liveBroadcastContent': 'none',
  'defaultLanguage': 'en',
  'localized': {'title': '스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE] Ep.94',
   'description': '스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE(스키즈 코드)] Ep.94\n\n✨ English, Japanese, Chinese, Spanish, Indonesian & Thai subtitles are available!\n\nListen to "DO IT" now☁️\nhttps://Stray-Kids.lnk.to/DOIT\n\nListen to "Do It (Remixes)" now🎊\nhttps://Stray-Kids.lnk.to/DoItRemixes\n\nStray Kids "DO IT"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DOIT/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DOIT/Spotify\n\nStray Kids "Do It (Remixes)"\niTunes & Apple Music: https://Stray-Kids.lnk.to/DoItRemixes/AppleMusic\nSpotify: https://Stray-Kids.lnk.to/DoItRemixes/Spotify\n\nStray Kids Official YouTube: https://www.youtube.com/c/StrayKids\nStray Kids Official Twitter: https://twitter.com/Stray_Kids\nStray Kids Official Instagram: https://www.instagram.com/realstraykids/\nStray Kids Official TikTok: https://www.tiktok.com/@jypestraykids\nStray Kids Official Facebook: https://www.facebook.com/JYPEStrayKids/\nStray Kids Official Threads: https://www.threads.com/@realstraykids\nStray Kids Official FANS (Android) https://play.google.com/store/apps/details?id=com.jype.fans\nStray Kids Official FANS (iOS) https://apps.apple.com/app/fans-for-fans-artists/id6474999628\n\n#StrayKids #스트레이키즈\n#스키즈코드 #SKZCODE\n#스키즈문화센터\n#SKZCommunityCenter\n#YouMakeStrayKidsStay\n\nCopyrights 2026 ⓒ JYP Entertainment. All Rights Reserved.'},
  'defaultAudioLanguage': 'ko'},
 'statistics': {'viewCount': '1979744',
  'likeCount': '185618',
  'favoriteCount': '0',
  'commentCount': '7034'}}

In [25]:
# Get the Video Stats
vid_info = vid_response['items'][0]
title = vid_info['snippet']['title']
stats = vid_info['statistics']

print(f"Title: {title}")
print(f"Views: {stats.get('viewCount')}")

Title: Hyunjin "LOVER" Video
Views: 5628876

In [27]:
vid_info.get("statistics", {})

{'viewCount': '5628876',
 'likeCount': '705144',
 'favoriteCount': '0',
 'commentCount': '53486'}

# Fetching Top Video Comments

In [18]:
# Extract Top Comments for One Video
comment_response = youtube.commentThreads().list(
        part="snippet",
        videoId=video_ids[0],
        maxResults=5, # Just 5 for testing
        order="relevance", 
        textFormat="plainText"
    ).execute()
display(comment_response)

{'kind': 'youtube#commentThreadListResponse',
 'etag': 'mrmH9XCu-1fkPZouSe4elV12-WI',
 'nextPageToken': 'Z2V0X3JhbmtlZF9zdHJlYW1zLS1Da1VJZ0FRVkY3ZlJPQm83Q2pjSTJGOFFnQVFZQnlJdEYxX3dwS1RRQTZPMk40WE41bzlyQWxSZ29TbEI2RmtST2t3ZVBycmlYY0d5OHpUbjczM3RvZGNPM0lNQkVBVVNCUWlvSUJnQUVnVUloeUFZQUJJRkNJa2dHQUFTQlFpSUlCZ0FFZ2NJaENBUUJSZ0JFZ1VJdXlBWUFCSUhDSVVnRUFFWUFR',
 'pageInfo': {'totalResults': 5, 'resultsPerPage': 5},
 'items': [{'kind': 'youtube#commentThread',
   'etag': '6mCl7JPmlraWmSn66bQKe3eMtX0',
   'id': 'UgxzqAIYGVrwVt2FLJ94AaABAg',
   'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
    'videoId': 'l8sSQAa1kNM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'tO8ScPftDqfY9dZazHClTjdzOFQ',
     'id': 'UgxzqAIYGVrwVt2FLJ94AaABAg',
     'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
      'videoId': 'l8sSQAa1kNM',
      'textDisplay': 'Haters: Hyunjin can’t sing\nHyunjin: Hold my paintbrush-',
      'textOriginal': 'Haters: Hyunjin can’t sing\nHyunjin: Hold my paintbrush-',
      'authorDisplayName': '@Hyunjins_left_pinkytoe0801',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/N2Ez1D3a3FKt8KAOkGj2Ymh5AQQIXG576nxrOxQ2G4i9pOi81BShm11XUqzlZBz2fEuTrLDSCQ=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@Hyunjins_left_pinkytoe0801',
      'authorChannelId': {'value': 'UCbzfjCdrNkyQA7Rz2Kdt81w'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 2652,
      'publishedAt': '2026-03-22T23:01:48Z',
      'updatedAt': '2026-03-22T23:01:48Z'}},
    'canReply': True,
    'totalReplyCount': 19,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'gv0GeBuGAIKqyAUjQWc-NT617Y8',
   'id': 'UgzzqjtLuFvH1cGK9UN4AaABAg',
   'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
    'videoId': 'l8sSQAa1kNM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'BsbtnT8GgR7t_cenM6onzDo3SmU',
     'id': 'UgzzqjtLuFvH1cGK9UN4AaABAg',
     'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
      'videoId': 'l8sSQAa1kNM',
      'textDisplay': 'WE NEED THIS ON SPOTIFY',
      'textOriginal': 'WE NEED THIS ON SPOTIFY',
      'authorDisplayName': '@just.m4y4143',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/3lc0y-8MG2Tu4pfNfGpSfaQ4x4ghp0WZJzBiuwNly-TC1V096ciohl_nsp3S-GiG7DSgDezqkA=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@just.m4y4143',
      'authorChannelId': {'value': 'UCUJ6x8TOt_6xIuDDo3FWkzQ'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 1907,
      'publishedAt': '2026-03-21T10:46:36Z',
      'updatedAt': '2026-03-21T10:46:36Z'}},
    'canReply': True,
    'totalReplyCount': 29,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'NuTLBrqAJjpe60r4mHabwv9zxvY',
   'id': 'UgwgW5Ab9cPe4ZT41vd4AaABAg',
   'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
    'videoId': 'l8sSQAa1kNM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': '07wkC4GetyY7WAc3u8PfdG4mb7A',
     'id': 'UgwgW5Ab9cPe4ZT41vd4AaABAg',
     'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
      'videoId': 'l8sSQAa1kNM',
      'textDisplay': 'Hyunjin didn’t just release a video; he released a feeling.\nThis is art.',
      'textOriginal': 'Hyunjin didn’t just release a video; he released a feeling.\nThis is art.',
      'authorDisplayName': '@b3starboof',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_kZ51ACGlbx2Jf5cKS2UnZZigPwdrHsCKJFKgqDLF0S72w=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@b3starboof',
      'authorChannelId': {'value': 'UC3AMS2joE2--DVtErwIijhQ'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 6602,
      'publishedAt': '2026-03-20T20:25:05Z',
      'updatedAt': '2026-03-20T20:25:05Z'}},
    'canReply': True,
    'totalReplyCount': 37,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'Vjb0hMqJ2IzpzA6_4e2DZrosdw0',
   'id': 'Ugw1jSnLJwSLu961TF94AaABAg',
   'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
    'videoId': 'l8sSQAa1kNM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'MVDxsrMmEY2-rYk0kIaxyVzp2pQ',
     'id': 'Ugw1jSnLJwSLu961TF94AaABAg',
     'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
      'videoId': 'l8sSQAa1kNM',
      'textDisplay': '#15 on youtube music chart. \n4 million in 4 days. \nZero promotion. \nDamn Hyunjin you killed it 🫶',
      'textOriginal': '#15 on youtube music chart. \n4 million in 4 days. \nZero promotion. \nDamn Hyunjin you killed it 🫶',
      'authorDisplayName': '@reny_grim',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_lfgUdjqO1PezbA3Hg7mYOjL4UXRkjvOgtToBw2ZvTw1t63Kabp3Gg5IdkHY5hfbJevCQ=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@reny_grim',
      'authorChannelId': {'value': 'UCsoU07s925q4Yqna4RYw59Q'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 1020,
      'publishedAt': '2026-03-24T09:10:08Z',
      'updatedAt': '2026-03-24T09:10:08Z'}},
    'canReply': True,
    'totalReplyCount': 18,
    'isPublic': True}},
  {'kind': 'youtube#commentThread',
   'etag': 'bGnsb7sb9GV0mugnjJFO0xtTOCM',
   'id': 'UgxIz-XFHSnA2c313694AaABAg',
   'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
    'videoId': 'l8sSQAa1kNM',
    'topLevelComment': {'kind': 'youtube#comment',
     'etag': 'mRKkLZ4CryKWZ_LJp9a84MLV_XU',
     'id': 'UgxIz-XFHSnA2c313694AaABAg',
     'snippet': {'channelId': 'UC9rMiEjNaCSsebs31MRDCRA',
      'videoId': 'l8sSQAa1kNM',
      'textDisplay': "his voice is so different here but it's insane!!",
      'textOriginal': "his voice is so different here but it's insane!!",
      'authorDisplayName': '@il.xz1',
      'authorProfileImageUrl': 'https://yt3.ggpht.com/l9kioKXuCu3KOu0mtC568GGSNqQiS_2nVAUKaZG6A56p-lahIKrDc761UKR7eqpEBQGdmz7rpg=s48-c-k-c0x00ffffff-no-rj',
      'authorChannelUrl': 'http://www.youtube.com/@il.xz1',
      'authorChannelId': {'value': 'UCJ9PJoSR6-Cn6eUP_6OVZUg'},
      'canRate': True,
      'viewerRating': 'none',
      'likeCount': 15616,
      'publishedAt': '2026-03-19T15:04:52Z',
      'updatedAt': '2026-03-19T15:04:52Z'}},
    'canReply': True,
    'totalReplyCount': 95,
    'isPublic': True}}]}

In [19]:
# Print The Top Comments
for item in comment_response.get('items', []):
    comment_text = item['snippet']['topLevelComment']['snippet']['textDisplay']
    # Cutting off at 100 characters for clean printing
    print(f"- {comment_text[:100]}...")

- Haters: Hyunjin can’t sing
Hyunjin: Hold my paintbrush-...
- WE NEED THIS ON SPOTIFY...
- Hyunjin didn’t just release a video; he released a feeling.
This is art....
- #15 on youtube music chart.
4 million in 4 days.
Zero promotion.
Damn Hyunjin you killed it 🫶...
- his voice is so different here but it's insane!!...

In [ ]:
# Put it into a DataFrame
# If we had run a loop over all videos, we'd have a list of dictionaries like this:
mock_video_data = [{
    "video_id": video_ids[0],
    "video_format": "Long-form",
    "title": title,
    "view_count": int(stats.get("viewCount", 0))
}]

df_videos = pd.DataFrame(mock_video_data)
display(df_videos)

      video_id video_format                  title content_pillar  view_count
0  l8sSQAa1kNM    Long-form  Hyunjin "LOVER" Video     Other/Misc     4422170

In [ ]:
# Fetch Stats for Only 100 Longform Videos to Analyze the Titles
sample_video_data = []

for video_id in video_ids:
    response = youtube.videos().list(
        part="snippet,statistics",
        id=video_id
    ).execute()
    
    snippet = response['items'][0]['snippet']
    stats = response['items'][0].get('statistics', {})
    
    sample_video_data.append({
        'video_id': video_id,
        'published_date': snippet['publishedAt'],
        'title': snippet['title'],
        'view_count': int(stats.get('viewCount', 0)),
        'like_count': int(stats.get('likeCount', 0)),
        'comment_count': int(stats.get('commentCount', 0)),
        'description': snippet['description'],
        'category_id': snippet['categoryId'],
        'tags': ",".join(snippet.get('tags', []))
    })

In [36]:
df_videos = pd.DataFrame(sample_video_data)

In [29]:
df_videos.loc[1, 'title']

'스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE] Ep.94'

In [37]:
df_videos.head(10)

,video_id,published_date,title,content_pillar,view_count,like_count,comment_count,description,category_id,tags
0,l8sSQAa1kNM,2026-03-19T15:00:08Z,"Hyunjin ""LOVER"" Video",Other/Misc,4458919,672927,51762,"현진(Hyunjin) ""LOVER"" Video\n\n[Credits]\nLyrics...",10,"JYP Entertainment,JYP,Stray Kids,스트레이 키즈,SKZ,스..."
1,9DSOFyLSv6Q,2026-03-19T10:59:58Z,스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE] ...,SKZ CODE,1752250,176497,6841,스키즈 문화센터 (SKZ Community Center) #2｜[SKZ CODE(스...,10,"Stray Kids,스트레이 키즈,SKZ,스키즈,방찬,BANG CHAN,리노,이민호..."
2,Jl5nNqajrV0,2026-03-18T10:59:56Z,[Stray Kids : SKZ-TALKER] Ep.81,SKZ-TALKER,563802,86181,3660,[Stray Kids(스트레이 키즈) : SKZ-TALKER(슼즈토커)] Ep.81...,10,"JYP Entertainment,JYP,Stray Kids,스트레이 키즈,SKZ,스..."
3,1tipk2X1aUo,2026-03-17T10:59:56Z,[RACHA LOG] Ep.17 청담꿀즈 : Bang Chan X Changbin ...,Other/Misc,711271,104361,3581,[RACHA LOG(라차로그)] Ep.17 청담꿀즈 : 방찬 X 창빈 X 승민 (B...,10,"Stray Kids,스트레이 키즈,SKZ,방찬,BANG CHAN,리노,이민호,LEE..."
4,bDbzZ_Dx4Ks,2026-03-15T11:00:18Z,Seungmin - 달리기 (윤상 Cover) | [SONG by 2] S#1,Other/Misc,741007,151678,10295,승민(Seungmin) - 달리기 (윤상 Cover) | [SONG by 2(송 바...,10,"Stray Kids,스트레이 키즈,SKZ,스키즈,방찬,BANG CHAN,리노,이민호..."
5,uB-XPe1K7SU,2026-03-12T10:59:56Z,스키즈 문화센터 (SKZ Community Center) #1｜[SKZ CODE] ...,SKZ CODE,2796113,264264,10108,스키즈 문화센터 (SKZ Community Center) #1｜[SKZ CODE(스...,10,"Stray Kids,스트레이 키즈,SKZ,스키즈,방찬,BANG CHAN,리노,이민호..."
6,X7jAms_f4Rc,2026-03-10T11:00:03Z,[RACHA LOG] Ep.16 쓰리라차 : Bang Chan X Changbin ...,Other/Misc,828258,117942,3586,[RACHA LOG(라차로그)] Ep.16 쓰리라차 : 방찬 X 창빈 X 한 (Ba...,10,"Stray Kids,스트레이 키즈,SKZ,방찬,BANG CHAN,리노,이민호,LEE..."
7,bSZL3ZZC8EE,2026-03-07T15:00:00Z,"I.N ""행복 뭐 별거 없네요(The Little Things)"" | [Stray ...",SKZ-PLAYER/RECORD,1081033,195744,12025,"아이엔(I.N) ""행복 뭐 별거 없네요(The Little Things)"" | [S...",10,"Stray Kids,스트레이 키즈,SKZ,방찬,BANG CHAN,리노,이민호,LEE..."
8,o66KJX1YJ3s,2026-03-05T10:59:57Z,"Stray Kids ""DO IT"" Recording Scene | Do It, 신선...",Other/Misc,1503301,180796,5425,"Stray Kids(스트레이 키즈) ""DO IT"" Recording Scene | ...",10,"Stray Kids,스트레이 키즈,SKZ,방찬,BANG CHAN,리노,이민호,LEE..."
9,ZV5IjNgpBFQ,2026-03-04T10:59:58Z,[Stray Kids : SKZ-TALKER] Ep.80,SKZ-TALKER,719482,102197,3083,[Stray Kids(스트레이 키즈) : SKZ-TALKER(슼즈토커)] Ep.80...,10,"JYP Entertainment,JYP,Stray Kids,스트레이 키즈,SKZ,스..."

In [45]:
df_videos.to_csv('../data/raw/df_videos_temporary.csv')

In [10]:
df_videos = pd.read_csv("../data/raw/df_videos_temporary.csv")
video_ids = list(df_videos['video_id'])
video_ids

['l8sSQAa1kNM',
 '9DSOFyLSv6Q',
 'Jl5nNqajrV0',
 '1tipk2X1aUo',
 'bDbzZ_Dx4Ks',
 'uB-XPe1K7SU',
 'X7jAms_f4Rc',
 'bSZL3ZZC8EE',
 'o66KJX1YJ3s',
 'ZV5IjNgpBFQ',
 'sKi1gEtnSAQ',
 'x-kl7fzEmaY',
 'h1li3NlTB0I',
 'ODoEa_1gPSc',
 'HFbirADU3_Q',
 'FEDQ14t58CA',
 'mUFKUJTMjWg',
 'PUUxE7EGP4Q',
 'OSUHqAvuSRI',
 'F6lf26nWk10',
 'Tsr3lBEn9ww',
 'IiqoozFOs1s',
 'v1xm6Pck-mo',
 'XOcH3lgw0KE',
 'bpnab0Aa5mE',
 'fETjgY83o7Q',
 'urNLPgalt6o',
 '9bHJc5Hv9Vw',
 '5Oio145WBB8',
 'nv6WtNmPXZU',
 'YsvbN665LZE',
 'ZeoHs2zfXPE',
 'wgfPkWSDUHU',
 'MI6_aH1JT7s',
 'HdgpH3_mZEs',
 'dxi4pB9b7eg',
 'uRJUVUlTevM',
 'PET396MCIV8',
 'TA7C2NBYw88',
 '3z27jOgXx-I',
 '5bzHeSphgUU',
 'ZqnBCh51qUw',
 'QNKTZSZ-X3s',
 'FR99OlxOVus',
 'xqu9eeGQxXc',
 '7oxJSrN2CNQ',
 'vPPEfLv1EpE',
 'k4IsJDwRKz4',
 'udFiiR4V6mg',
 'wIJ2TcnDKPs',
 'FCXd9nXSWTM',
 'mf967jPZrCk',
 'eHmQ_b0LkUA',
 'FECQ9MmbC4Y',
 'kaBPTrvzf8c',
 'ZSy5AcukDjI',
 'FnWKcU7ayH0',
 'Hw4Qwy_Kr-8',
 'XZL0Dvxs7jY',
 'Csaxd97bVJE',
 '1ydl2uTMPGo',
 'U9-7JBGRyMc',
 'IUreR3zoD3s',
 'pPfpE6pOapA',
 'XU08DOMg2EY',
 'RJvYHFKknfM',
 'w9eOsEFpM6A',
 'V77feEklVzA',
 'y7z55mObLO8',
 '2kQENtCRu6Y',
 'i2FGGGhHduE',
 '0oTtNyRhpm8',
 't3QYengDjr0',
 'ECC-hru050A',
 '9gerQFZUXjc',
 'iip2qL9cB7Q',
 '1EP5hxH6O7M',
 'dLgCTUvBdkU',
 'pVNEUDePkSk',
 'i6ywIzsx1NI',
 'krVcQgnK3EU',
 'Y1mYx1pJVHk',
 '2c6V6rC-dXg',
 'lT2OKzBpqQA',
 '0e68vNHgIkk',
 'kuSUU0oe1J0',
 '_YOUhOuFNs4',
 '70wchLxP4io',
 'cc7f4fX1ORA',
 'CUX4XYIW6gw',
 'zMJhEXR7meQ',
 'eMki9Cw_m-I',
 'iP6Ubt6Z-XM',
 'yL2Dt8wjgJQ',
 'r-qO8McDYgE',
 'BR_7CF8v744',
 '8-PUkLkCDW8',
 'y-rPpGpnSg0',
 'cW9D6_g6MR0',
 'ciRftriyejM']

# Fetching Video Transcripts

In [4]:
transcript_data = []

ytt_api = YouTubeTranscriptApi()

# Fetch the list of available transcripts for the video
available_transcript = ytt_api.list(video_ids[0])
available_transcript

In [6]:
# Find English first, fallback to Korean
transcript = available_transcript.find_transcript(['en', 'ko'])
transcript

In [7]:
# Fetch the actual transcript data chunks
transcript_chunks = transcript.fetch()
transcript_chunks

FetchedTranscript(snippets=[FetchedTranscriptSnippet(text='Yeah yeah yeah yeah', start=12.417, duration=1.625), FetchedTranscriptSnippet(text='I’m running in the rain yeah', start=14.042, duration=1.583), FetchedTranscriptSnippet(text='Hoping it washes away my broken heart ', start=15.625, duration=2.958), FetchedTranscriptSnippet(text='You once did love me, though? Right, right?', start=18.583, duration=7.334), FetchedTranscriptSnippet(text='Lover lover lover is hurt ’cause she went away', start=25.917, duration=3.416), FetchedTranscriptSnippet(text='Loved her loved her loved her so much until that rainy day', start=29.333, duration=3.334), FetchedTranscriptSnippet(text='Lover lover lover dies ’cause there’s no way', start=32.667, duration=3.25), FetchedTranscriptSnippet(text='Lover lover love is gone no matter what I say', start=35.917, duration=3.666), FetchedTranscriptSnippet(text='Oh, this is too much to handle while sober', start=39.583, duration=2.417), FetchedTranscriptSnippet(text='I don’t want to drink no more no more no more', start=42.0, duration=2.917), FetchedTranscriptSnippet(text='Why’re you acting like it’s me', start=44.917, duration=2.041), FetchedTranscriptSnippet(text='It’s all my fault, you mean?', start=46.958, duration=1.5), FetchedTranscriptSnippet(text='Then again, you were always like that   ', start=48.458, duration=3.5), FetchedTranscriptSnippet(text='Why why is it not me', start=51.958, duration=5.5), FetchedTranscriptSnippet(text='In your eyes I’m searching for a reason ooh ooh ooh ooh', start=57.458, duration=6.834), FetchedTranscriptSnippet(text='Yeah yeah yeah yeah', start=64.292, duration=1.583), FetchedTranscriptSnippet(text='I’m running in the rain yeah', start=65.875, duration=1.625), FetchedTranscriptSnippet(text='Hoping it washes away my broken heart ', start=67.5, duration=3.0), FetchedTranscriptSnippet(text='You once did love me, though? Right, right?', start=70.5, duration=7.333), FetchedTranscriptSnippet(text='Lover lover lover is hurt ’cause she went away', start=77.833, duration=3.5), FetchedTranscriptSnippet(text='Loved her loved her loved her so much until that rainy day', start=81.333, duration=3.25), FetchedTranscriptSnippet(text='Lover lover lover dies ’cause there’s no way', start=84.583, duration=3.209), FetchedTranscriptSnippet(text='Lover lover love is gone no matter what i say', start=87.792, duration=3.375), FetchedTranscriptSnippet(text='Lover lover lover needs a hug cause she‘s gone away', start=91.167, duration=3.125), FetchedTranscriptSnippet(text='Loved her loved her loved her so much in my rose-tinted memories', start=94.292, duration=3.291), FetchedTranscriptSnippet(text='Lover lover lover dies ’cause there’s no way', start=97.583, duration=3.25), FetchedTranscriptSnippet(text='Lover lover love is gone no matter what I say', start=100.833, duration=3.292), FetchedTranscriptSnippet(text='Can I let go of you now?', start=104.125, duration=2.625), FetchedTranscriptSnippet(text='We both know, honestly, things were off from the beginning', start=106.75, duration=3.708), FetchedTranscriptSnippet(text='That first excitement, the promises we made', start=110.458, duration=2.75), FetchedTranscriptSnippet(text='Memories that no one can turn back', start=113.208, duration=3.917), FetchedTranscriptSnippet(text='Tell me why, what bothered you so much', start=117.125, duration=3.125), FetchedTranscriptSnippet(text='Tell me how, how things should have been done', start=120.25, duration=3.25), FetchedTranscriptSnippet(text='Tell me why, what made you change so easily', start=123.5, duration=3.333), FetchedTranscriptSnippet(text='Tell me how to get out of this', start=126.833, duration=1.709), FetchedTranscriptSnippet(text='Now I’m done with you', start=128.542, duration=1.125), FetchedTranscriptSnippet(text='Yeah yeah yeah yeah', start=129.667, duration=1.208), FetchedTranscriptSnippet(text='I’m running in the rain yeah', start=130.875, duration=1.417), FetchedTranscriptSnippet(text='Hoping it washes away my broken heart ', start=132.292, duration=3.041), FetchedTranscriptSnippet(text='You once did love me, though? Right, right?', start=135.333, duration=7.625), FetchedTranscriptSnippet(text='Lover lover lover is hurt ’cause she went away', start=142.958, duration=3.209), FetchedTranscriptSnippet(text='Loved her loved her loved her so much until that rainy day', start=146.167, duration=3.25), FetchedTranscriptSnippet(text='Lover lover lover dies ’cause there’s no way', start=149.417, duration=3.291), FetchedTranscriptSnippet(text='Lover lover love is gone no matter what I say', start=152.708, duration=3.25), FetchedTranscriptSnippet(text='Lover lover lover needs a hug ’cause she‘s gone away', start=155.958, duration=3.167), FetchedTranscriptSnippet(text='Loved her loved her loved her so much in my rose-tinted memories', start=159.125, duration=3.292), FetchedTranscriptSnippet(text='Lover lover lover dies ’cause there’s no way', start=162.417, duration=3.375), FetchedTranscriptSnippet(text='Lover lover love is gone no matter what I say', start=165.792, duration=3.416)], video_id='l8sSQAa1kNM', language='English', language_code='en', is_generated=False)

In [9]:
type(transcript_chunks)

youtube_transcript_api._transcripts.FetchedTranscript

In [8]:
# Join the chunked dictionary elements into a single continuous text string
full_transcript = " ".join([segment.text for segment in transcript_chunks])
full_transcript

'Yeah yeah yeah yeah I’m running in the rain yeah Hoping it washes away my broken heart  You once did love me, though? Right, right? Lover lover lover is hurt ’cause she went away Loved her loved her loved her so much until that rainy day Lover lover lover dies ’cause there’s no way Lover lover love is gone no matter what I say Oh, this is too much to handle while sober I don’t want to drink no more no more no more Why’re you acting like it’s me It’s all my fault, you mean? Then again, you were always like that    Why why is it not me In your eyes I’m searching for a reason ooh ooh ooh ooh Yeah yeah yeah yeah I’m running in the rain yeah Hoping it washes away my broken heart  You once did love me, though? Right, right? Lover lover lover is hurt ’cause she went away Loved her loved her loved her so much until that rainy day Lover lover lover dies ’cause there’s no way Lover lover love is gone no matter what i say Lover lover lover needs a hug cause she‘s gone away Loved her loved her loved her so much in my rose-tinted memories Lover lover lover dies ’cause there’s no way Lover lover love is gone no matter what I say Can I let go of you now? We both know, honestly, things were off from the beginning That first excitement, the promises we made Memories that no one can turn back Tell me why, what bothered you so much Tell me how, how things should have been done Tell me why, what made you change so easily Tell me how to get out of this Now I’m done with you Yeah yeah yeah yeah I’m running in the rain yeah Hoping it washes away my broken heart  You once did love me, though? Right, right? Lover lover lover is hurt ’cause she went away Loved her loved her loved her so much until that rainy day Lover lover lover dies ’cause there’s no way Lover lover love is gone no matter what I say Lover lover lover needs a hug ’cause she‘s gone away Loved her loved her loved her so much in my rose-tinted memories Lover lover lover dies ’cause there’s no way Lover lover love is gone no matter what I say'

In [2]:
datetime.now(timezone.utc).isoformat()

'2026-03-29T18:33:11.234492+00:00'

In [5]:
for i in range(0, 223, 5):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220